// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  quote: dynamic(() => import("./Quote")),
  testing_slice: dynamic(() => import("./TestingSlice")),
  text: dynamic(() => import("./Text")),
  video_block: dynamic(() => import("./VideoBlock")),
};
